# Generated by Django 4.1.1 on 2023-01-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Site name')),
                ('website', models.CharField(blank=True, max_length=30, null=True, verbose_name='Website URL')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Company address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Company number')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='Company email')),
                ('founder', models.CharField(blank=True, max_length=30, null=True, verbose_name='Company founder')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='main/')),
                ('year', models.CharField(blank=True, max_length=15, null=True)),
                ('btc', models.CharField(blank=True, max_length=60, null=True, verbose_name='Bitcoin address')),
                ('eth', models.CharField(blank=True, max_length=60, null=True, verbose_name='Ethereum address')),
                ('usdt', models.CharField(blank=True, max_length=60, null=True, verbose_name='USDT address')),
            ],
            options={
                'verbose_name_plural': 'Site features',
            },
        ),
    ]
