# Generated by Django 4.1.1 on 2023-01-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(default='client', max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='testimonies/')),
            ],
            options={
                'verbose_name': 'Testimony',
                'verbose_name_plural': 'Testimonies',
            },
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name_plural': 'Site Features'},
        ),
    ]
