# Generated by Django 4.1.1 on 2023-01-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_testimony_alter_site_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonies/'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='title',
            field=models.CharField(default='Client', max_length=20),
        ),
    ]
