# Generated by Django 4.1.1 on 2023-01-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_testimony_image_alter_testimony_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='image',
            field=models.ImageField(default='static/img/homepage/7.jpg', upload_to='testimonies/'),
        ),
    ]
