# Generated by Django 4.1.1 on 2023-01-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_testimony_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonies/'),
        ),
    ]
