# Generated by Django 4.1.1 on 2023-01-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(default='siteName', max_length=30, verbose_name='Site name'),
        ),
    ]
